name: CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: swiftlint lint --reporter github-actions-logging --strict
  build:
    name: Build & Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@latest
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
