name: Lint, Build & Test

on: push

jobs:
  macos:
    name: Lint, Build & Test
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@v1
      - uses: actions/checkout@v3
      - name: Lint
        run: swiftlint lint --strict
      - name: Build
        run: swift build
#      - name: Test
#        run: swift test
